### ISSUE TITLE
also push to github

### ISSUE THREAD

**Issue by purpleKarrot** [ryppl/boost-svn2git#5]
github also has a nice graphical rendering of branches

**Comment by dabrahams** [comment]
Where?

**Comment by purpleKarrot** [comment]
https://github.com/boostorg would be the right place, no?
I want to make sure that all repositories exist before I add the required
push code to the CMakeLists.txt file.

**Comment by dabrahams** [comment]
Sure.  What I mean is, "Where can I see that nice revision history?"

**Comment by purpleKarrot** [comment]
example: https://github.com/ryppl/ryppl/network

**Comment by dabrahams** [comment]
FWIW, GitHub themselves temper expectations.  For example, this support reply from 23 Jan 2010.  

> From: Tekkub
> Subject: Network graph usability issues
> 
> The network graph is designed primarily to help you see what commits
> exist in forks that aren't in the base repo.  It's not intended to be
> a substitue for gitk or gitx run locally.

IMO this should be considered a low-priority issue.
