### ISSUE TITLE
Execute cutover from svn to git repos

### ISSUE THREAD

**Issue by Beman** [ryppl/boost-svn2git#8]
These events need to happen more or less simultaneously:
- [ ] The Subversion repo becomes read-only.
- [ ] The Git repo becomes live.
- [ ] The conversion scripts stop running.
- [ ] The www.boost.org website is updated, with references and instructions relating to svn and the svn repo replace by references and instructions for git and the git repos.
- [ ] The svn.boost.org/trac/boost/wiki is updated,  with references and instructions relating to svn and the svn repo replace by references and instructions for git and the git repos.
- [ ] The inspect scripts are switched from the svn repo scripts to the git repo scripts.
- [ ] The regression reporting scripts are switched from the svn repo scripts to the git repo scripts.
- [ ] An announcement of the cutover is posted to the developer, user, and announce mailing lists.

**Comment by dabrahams** [comment]
Why is this closed?

**Comment by Beman** [comment]
On Thu, Feb 7, 2013 at 3:53 PM, Dave Abrahams notifications@github.comwrote:

> Why is this closed?

Because it is going to become a milestone, and I didn't see a way to
convert an issue to a milestone.

--Beman
